-- CreateTable
CREATE TABLE `customer_insight` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `age` ENUM('UNDER_30', 'FROM_30_TO_40', 'FROM_40_TO_60', 'ABOVE_60') NOT NULL,
    `time` ENUM('SINCE_CHILDHOOD', 'SINCE_PUBERTY', 'AFTER_GIVING_BIRTH', 'AFTER_BIRTH_AND_PERIMENOPAUSE') NOT NULL,
    `category` ENUM('CUSTOMER_STATUS', 'CONCLUDE', 'SOLUTION') NOT NULL,
    `content` LONGTEXT NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
