-- AlterTable
ALTER TABLE `category` MODIFY `category` ENUM('INSIGHT_MOTHER', 'HANDLE_REJECTION', 'INTRODUCE_SOLUTION', 'CONFIRM') NOT NULL;

-- AlterTable
ALTER TABLE `proposal` MODIFY `categoryType` ENUM('INSIGHT_MOTHER', 'HANDLE_REJECTION', 'INTRODUCE_SOLUTION', 'CONFIRM') NOT NULL;

-- CreateTable
CREATE TABLE `insight_2` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `keyword` VARCHAR(191) NOT NULL,
    `explain` LONGTEXT NOT NULL,
    `solution` LONGTEXT NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
